name: Update Projects from Google Sheet

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  update-projects:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      id-token: write  # Add this for secrets access
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas  # Add pandas for better CSV handling
    
    - name: Run sheet converter
      run: |
        mkdir -p data  # Ensure data directory exists
        python sheets_to_json.py
      env:
        SHEET_ID: ${{ secrets.SHEET_ID }}
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/projects.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update projects from Google Sheet - $(date)"
          git push
        fi
